name: Fake release
on:
  push:     
jobs:
  fake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Latest
        id: newest
        uses: ./.github/actions/validate-version
        with:
          version: 5.3.0
      - name: Prerelease
        id: prerelease
        uses: ./.github/actions/validate-version
        with:
          version: 5.3.0-alpha.4
      - name: Previous Major
        id: prev-major
        uses: ./.github/actions/validate-version
        with:
          version: 4.33.5
      - name: Illegal
        id: illegal
        uses: ./.github/actions/validate-version
        with:
          version: 4.32.115
      - name: Output
        if: ${{ always() }}
        run: |
          echo "Newest: Major ${{ steps.newest.outputs.major }}, Minor ${{ steps.newest.outputs.minor }}, Patch ${{ steps.newest.outputs.patch }}, Prerelease '${{ steps.newest.outputs.prerelease }}, Tags [${{ steps.newest.outputs.tags }}"
          echo "Prerelease: Major ${{ steps.prerelease.outputs.major }}, Minor ${{ steps.prerelease.outputs.minor }}, Patch ${{ steps.prerelease.outputs.patch }}, Prerelease '${{ steps.prerelease.outputs.prerelease }}, Tags [${{ steps.prerelease.outputs.tags }}"
          echo "PrevMajor: Major ${{ steps.prev-major.outputs.major }}, Minor ${{ steps.prev-major.outputs.minor }}, Patch ${{ steps.prev-major.outputs.patch }}, Prerelease '${{ steps.prev-major.outputs.prerelease }}, Tags [${{ steps.prev-major.outputs.tags }}"
