name: Fake release
on:
  push:     
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate version
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Newest
        uses: ./.github/workflows/validate-version.yml
        with:
          version: 5.3.0
      - name: Preview
        uses: ./.github/workflows/validate-version.yml
        with:
          version: 5.3.0-alpha.4
      - name: Previous Major
        uses: ./.github/workflows/validate-version.yml
        with:
          version: 4.33.5
      - name: Illegal version
        uses: ./.github/workflows/validate-version.yml
        with:
          version: 4.32.115
        
