name: Fake release
on:
  push:     
jobs:
  newest:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 5.3.0
  prerelease:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 5.3.0-alpha.4
  prev-major:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 4.33.5
  illegal:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 4.32.115
  done:
    needs: [newest, prerelease, prev-major]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Newest: Major ${{ jobs.newest.outputs.major }}, Minor ${{ jobs.newest.outputs.minor }}, Patch ${{ jobs.newest.outputs.patch }}, Prerelease '${{ jobs.newest.outputs.prerelease }}, Tags [${{ jobs.newest.outputs.tags }}"
          echo "Prerelease: Major ${{ jobs.prerelease.outputs.major }}, Minor ${{ jobs.prerelease.outputs.minor }}, Patch ${{ jobs.prerelease.outputs.patch }}, Prerelease '${{ jobs.prerelease.outputs.prerelease }}, Tags [${{ jobs.prerelease.outputs.tags }}"
          echo "PrevMajor: Major ${{ jobs.prev-major.outputs.major }}, Minor ${{ jobs.prev-major.outputs.minor }}, Patch ${{ jobs.prev-major.outputs.patch }}, Prerelease '${{ jobs.prev-major.outputs.prerelease }}, Tags [${{ jobs.prev-major.outputs.tags }}"
