name: Fake release
on:
  push:     
jobs:
  newest:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 5.3.0
  prerelease:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 5.3.0-alpha.4
  prev-major:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 4.33.5
  illegal:
    uses: ./.github/workflows/validate-version.yml
    with:
      version: 4.32.115
  done:
    needs: [newest, prerelease, prev-major]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Newest: Major ${{ needs.newest.outputs.major }}, Minor ${{ needs.newest.outputs.minor }}, Patch ${{ needs.newest.outputs.patch }}, Prerelease '${{ needs.newest.outputs.prerelease }}, Tags [${{ needs.newest.outputs.tags }}"
          echo "Prerelease: Major ${{ needs.prerelease.outputs.major }}, Minor ${{ needs.prerelease.outputs.minor }}, Patch ${{ needs.prerelease.outputs.patch }}, Prerelease '${{ needs.prerelease.outputs.prerelease }}, Tags [${{ needs.prerelease.outputs.tags }}"
          echo "PrevMajor: Major ${{ needs.prev-major.outputs.major }}, Minor ${{ needs.prev-major.outputs.minor }}, Patch ${{ needs.prev-major.outputs.patch }}, Prerelease '${{ needs.prev-major.outputs.prerelease }}, Tags [${{ needs.prev-major.outputs.tags }}"
