name: Conditional
on:
  push:
jobs:
  build:
    name: ${{ matrix.name || matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ windows-2019, ubuntu-20.04 ]
        include:
          os: windows-2022
          name: WindowsSpecial
      fail-fast: false
    steps:
      - run: echo "hi"
