name: Mark closed small decision PRs
on:
  pull_request:
    types: [ closed ]
permissions:
  pull-requests: write
jobs:
  mark:
    runs-on: ubuntu-latest
    steps:
      - name: Mark small decisions with label
        uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          script: |
            const smallDecisionRegex = /\[[Xx]\]\s+A\ssmall\s+decision/i;
            const labelName = 'Merged small decision';
            
            console.log(JSON.stringify(context));
            
            let pr = context.payload.pull_request;
            let body = pr.body;
            
            let isSmallTask = body && body.match(smallDecisionRegex);
            if (!isSmallTask) {
              return;
            }
            
            if (!pr.merged) {
              return;
            }
            
            let repo = context.payload.repository;
            
            await github.rest.issues.addLabels({
              owner: repo.owner.login,
              repo: repo.name,
              issue_number: pr.number,
              labels: [ labelName ]
            });
            
