name: push
on:
  push:
jobs:
  build:
    name: Test Concurrency
    runs-on: ubuntu-latest
    concurrency: ${{ matrix.concurrency-value || (github.ref + '-' + github.run_id) }}
    strategy:
      matrix: 
        include:
          - name: A
          - name: B
          - name: C
          - name: D
          - name: E
          - name: F
          - name: G
          - name: Concurrent-A1
            concurrency-value: A
          - name: Concurrent-A2
            concurrency-value: A
          - name: Concurrent-A3
            concurrency-value: A
          - name: Concurrent-B1
            concurrency-value: B
          - name: Concurrent-B2
            concurrency-value: B
          - name: Concurrent-B3
            concurrency-value: B
      fail-fast: false
    steps:
      - shell: pwsh
        run: |
          echo "${{ matrix.name }}"
          echo "Start Time $(Get-Date)"
          sleep 60
          echo "End Time $(Get-Date)"
      
